version: '2'
catalog:
  name: Pipeline
  version: 1.0.0
  minimum_rancher_version: 1.6.13-rc2
  description: "Rancher Pipeline"
  questions:
    - variable: SLAVES
      type: "int"
      default: "1"
      label: "# of slaves"
      description: "How many jenkins slaves to run ci tasks. At least 1."
    - variable: EXECUTORS
      type: "int"
      default: "2"
      label: "# of executors"
      description: "How many executors on a jenkins slave"
    - variable: JENKINS_PORT
      type: "int"
      label: "Jenkins Public Port"
      description: "Public port for Jenkins master's http port.for DEBUG purpose,remove when release."
    - variable: HOST_LABEL
      label: "Host with Label to put pipeline components on"
      description: |
        Run pipeline components on Host with specific labels. 
        Example: 'pipeline=true'
      required: false
      default: ""
      type: "string"
services:
  jenkins-slave:
#{{- if ge .Values.SLAVES "1" }}
    scale: ${SLAVES}
#{{- else }}
    scale: 1
#{{- end }}
